import { db, auth } from "@/lib/firebase";
import { collection, addDoc, getDocs, query, orderBy, limit, deleteDoc, doc, where } from "firebase/firestore";
import { generateUUID } from "@/lib/utils";

// Forensics Data Interface
export interface ForensicsData {
  dns: {
    a: string[];
    mx: string[];
    txt: string[];
  };
  age: {
    days?: number;
    created_date?: string;
    registrar?: string;
  };
  geolocation?: {
    country: string;
    isp: string;
  };
}

export interface ThreatAudit {
  scan_time: string;
  sources: {
    abuseipdb?: {
      scanned: boolean;
      score: number; // 0-100
      verdict: 'clean' | 'suspicious' | 'malicious';
    };
    virustotal?: {
      scanned: boolean;
      malicious: number;
      suspicious: number;
      verdict: 'clean' | 'suspicious' | 'malicious';
    };
    google_safe_browsing?: {
      scanned: boolean;
      matches: string[]; // threat types found
    };
    phishtank?: {
      scanned: boolean;
      found: boolean;
      verified: boolean;
    };
  };
}

export interface DetectionResult {
  label: 'safe' | 'suspicious' | 'phishing';
  risk_percentage: number;
  confidence: number;
  input_type: string;
  top_reasons: string[];
  forensics?: ForensicsData; // New Optional Field
  threat_audit?: ThreatAudit; // NEW: Audit of third-party checks
  isFallback?: boolean; // NEW: Indicates if the result was generated by local heuristic fallback
  details: {
    indicators: { name: string; severity: 'low' | 'medium' | 'high'; description: string }[];
    analysis_summary: string;
  };
}

export interface ScanHistoryItem {
  id: string;
  content: string;
  content_preview: string;
  result: DetectionResult;
  scanned_at: string;
}

// DNS-over-HTTPS (DoH) via Cloudflare
async function fetchDNSRecords(domain: string) {
  const records = { a: [] as string[], mx: [] as string[], txt: [] as string[] };

  try {
    // Helper to query Cloudflare
    const query = async (type: string) => {
      const res = await fetch(`https://cloudflare-dns.com/dns-query?name=${domain}&type=${type}`, {
        headers: { 'Accept': 'application/dns-json' }
      });
      const data = await res.json() as { Answer?: { data: string }[] };
      return data.Answer ? data.Answer.map((a) => a.data) : [];
    };

    const [a, mx, txt] = await Promise.all([query('A'), query('MX'), query('TXT')]);
    records.a = a;
    records.mx = mx;
    records.txt = txt;
  } catch (e) {
    console.warn('DNS lookup failed:', e);
  }
  return records;
}

// Domain Age verification using RDAP and WHOIS via backend plugin
async function fetchDomainAge(domain: string) {
  // 1. Check Mock Whitelist (speed optimization)
  if (['google.com', 'facebook.com', 'amazon.com', 'paypal.com', 'microsoft.com', 'apple.com', 'wikipedia.org'].includes(domain)) {
    return {
      days: 10000,
      created_date: 'Pre-2000',
      registrar: 'MarkMonitor (Verified)'
    };
  }

  try {
    // 2. Call local Vite Plugin proxy which securely runs node's 'net' module
    const res = await fetch(`/api/whois?domain=${encodeURIComponent(domain)}`);
    if (res.ok) {
       const data = await res.json();
       if (data && typeof data.days === 'number') {
         return {
           days: data.days,
           created_date: data.created_date || 'Unknown',
           registrar: data.registrar || 'Unknown'
         };
       }
    }
  } catch (e) {
    console.warn('Backend WHOIS/RDAP check failed:', e);
  }

  // 3. Fallback
  return {
    days: 0, // 0 implies "Unknown/New" - trigger caution but not instant block without other signals
    created_date: 'Unknown',
    registrar: 'Unknown'
  };
}

async function getForensics(domain: string): Promise<ForensicsData> {
  const [dns, age] = await Promise.all([
    fetchDNSRecords(domain),
    fetchDomainAge(domain)
  ]);

  return { dns, age };
}

// Lookalike character substitutions used in homograph/lookalike attacks
const LOOKALIKE_SUBSTITUTIONS: Record<string, string[]> = {
  'a': ['4', '@', 'ą', 'а'],
  'e': ['3', '€', 'є', 'е'],
  'i': ['1', 'l', '!', 'і'],
  'o': ['0', 'ο', 'о'],
  's': ['5', '$', 'ѕ'],
  'l': ['1', 'i', '|'],
  'g': ['9', 'q'],
  'b': ['8', '6'],
  't': ['7', '+'],
  'z': ['2'],
  'p': ['9', 'ρ'],
  'n': ['ո'],
};

const OFFICIAL_BRAND_DOMAINS: Record<string, string[]> = {
  'google': ['google.com', 'accounts.google.com'],
  'amazon': ['amazon.com', 'aws.amazon.com'],
  'paypal': ['paypal.com', 'www.paypal.com'],
  'microsoft': ['microsoft.com', 'login.microsoftonline.com'],
  'apple': ['apple.com', 'icloud.com'],
  'facebook': ['facebook.com', 'www.facebook.com'],
  'twitter': ['twitter.com', 'x.com'],
  'linkedin': ['linkedin.com', 'www.linkedin.com'],
  'github': ['github.com', 'www.github.com'],
};

const KNOWN_BRANDS = ['google', 'amazon', 'paypal', 'microsoft', 'apple', 'facebook', 'twitter', 'linkedin', 'github', 'netflix', 'coinbase'];

function normalizeLookalikeCharacters(domain: string): string {
  let normalized = domain.toLowerCase();
  for (const [baseChar, lookalikes] of Object.entries(LOOKALIKE_SUBSTITUTIONS)) {
    for (const lookalike of lookalikes) {
      normalized = normalized.split(lookalike).join(baseChar);
    }
  }
  return normalized;
}

function detectLookalikeAttack(domain: string): { isLookalike: boolean; targetBrand?: string; substitutions?: string[] } {
  const lowerDomain = domain.toLowerCase();
  const normalized = normalizeLookalikeCharacters(domain);

  // Check if THIS EXACT domain is legitimate first
  for (const brand of KNOWN_BRANDS) {
    const officialDomains = OFFICIAL_BRAND_DOMAINS[brand] || [];
    if (officialDomains.some(official => lowerDomain === official || lowerDomain === `www.${official}`)) {
      return { isLookalike: false };
    }
  }

  // Check if domain has lookalike characters
  if (normalized === lowerDomain) {
    return { isLookalike: false };
  }

  const normalizedBaseDomain = normalized.split('.')[0];

  for (const brand of KNOWN_BRANDS) {
    if (normalizedBaseDomain === brand || normalizedBaseDomain.startsWith(brand)) {
      const substitutions: string[] = [];
      for (let i = 0; i < lowerDomain.length && i < normalized.length; i++) {
        if (lowerDomain[i] !== normalized[i]) {
          substitutions.push(`${lowerDomain[i]}→${normalized[i]}`);
        }
      }
      return {
        isLookalike: true,
        targetBrand: brand,
        substitutions: [...new Set(substitutions)],
      };
    }
  }

  return { isLookalike: false };
}

// Real URL expansion using unshorten.me API
async function expandShortUrl(shortUrl: string): Promise<string> {
  const shorteners = ['bit.ly', 'tinyurl.com', 'goo.gl', 't.co', 'ow.ly', 'is.gd', 'buff.ly'];
  const isShortened = shorteners.some(s => shortUrl.includes(s));

  if (!isShortened) return shortUrl;

  try {
    const cleanUrl = shortUrl.startsWith('http') ? shortUrl : `https://${shortUrl}`;
    const res = await fetch(`https://unshorten.me/s/${encodeURIComponent(cleanUrl)}`);
    if (res.ok) {
      const resolved = await res.text();
      if (resolved && resolved !== 'Invalid URL') {
        return resolved.trim();
      }
    }
  } catch (e) {
    console.warn('Failed to unshorten URL via API:', e);
  }

  // Backward compatible static fallback
  const knownMalicious = {
    'bit.ly/secure-login': 'phishing-site.com',
    'tinyurl.com/reset-pass': 'evil-site.net',
  };

  for (const [key, val] of Object.entries(knownMalicious)) {
    if (shortUrl.includes(key)) return val;
  }

  return shortUrl; // Return original if cannot expand
}

function calculateLogisticRegression(features: Record<string, number>): number {
  const weights: Record<string, number> = {
    urlLength: 0.8,
    numDots: 0.5,
    hasIp: 3.0,
    urlKeywords: 1.5,
    domainAge: 2.0,
    urgency: 1.0,
    linkDiscrepancy: 1.5,
    senderReputation: 1.0,
    suspiciousAttachments: 1.5,
    credentialRequest: 2.0,
    cryptoRequest: 2.5,
    punycode: 3.0,
    brandMismatch: 2.5,
    disposableHost: 1.5,
    lookalike: 3.5,
    semanticMismatch: 1.5
  };
  let z = -3.5; // Baseline safe
  for (const [key, value] of Object.entries(features)) {
    if (weights[key]) {
      z += weights[key] * value;
    }
  }
  return 1 / (1 + Math.exp(-z));
}

// Simple local detection for fallback/testing
export async function performLocalDetection(content: string, type: string): Promise<DetectionResult> {
  const indicators: { name: string; severity: 'low' | 'medium' | 'high'; description: string }[] = [];
  
  const features = {
    urlLength: 0,
    numDots: 0,
    hasIp: 0,
    urlKeywords: 0,
    domainAge: 0,
    urgency: 0,
    linkDiscrepancy: 0,
    senderReputation: 0,
    suspiciousAttachments: 0,
    credentialRequest: 0,
    cryptoRequest: 0,
    punycode: 0,
    brandMismatch: 0,
    disposableHost: 0,
    lookalike: 0,
    semanticMismatch: 0
  };

  const lowerContent = content.toLowerCase();

  // NLP features (Text/Content)
  const urgencyKeywords = ['immediate', 'urgent', '24 hours', 'suspended', 'locked', 'act now', 'unusual activity'];
  if (urgencyKeywords.some(kw => lowerContent.includes(kw))) {
    features.urgency = 1;
    indicators.push({
      name: 'High-Pressure Language',
      severity: 'medium',
      description: 'Contains language creating a false sense of urgency or threat'
    });
  }

  const grammarIssues = ['kindly do the needful', 'am writing to you', 'inheritance'];
  if (features.urgency === 1 && grammarIssues.some(kw => lowerContent.includes(kw))) {
    features.semanticMismatch = 1;
    indicators.push({
      name: 'Semantic Mismatch',
      severity: 'high',
      description: 'Combination of high urgency and poor/unusual grammar'
    });
  }
  
  if (/password|ssn|social security|credit card|bank account/i.test(content)) {
    features.credentialRequest = 1;
    indicators.push({
      name: 'Credential Request',
      severity: 'high',
      description: 'Explicitly requests sensitive personal information'
    });
  }

  // Crypto matching (BTC, ETH, LTC)
  if (/(?:bc1|[13])[a-zA-HJ-NP-Z0-9]{25,39}|0x[a-fA-F0-9]{40}|[LM3][a-km-zA-HJ-NP-Z1-9]{26,33}/.test(content)) {
    features.cryptoRequest = 1;
    indicators.push({
      name: 'Cryptocurrency Address',
      severity: 'high',
      description: 'Mentions untraceable cryptocurrency wallet addresses'
    });
  }

  if (/@/.test(content) && (/from:|sender:/i.test(content))) {
    const emailMatch = content.match(/[\w.-]+@[\w.-]+\.\w+/g);
    if (emailMatch) {
      if (emailMatch.some(email => email.includes('gmail.com') || email.includes('yahoo.com'))) {
        features.senderReputation = 1;
        indicators.push({
          name: 'Suspicious Sender Reputation',
          severity: 'medium',
          description: `Free email provider used for potentially official communication`
        });
      }
    }
  }
  
  if (/\.(zip|exe|scr|vbs|js|bat|cmd|msi|rar)$/i.test(content)) {
    features.suspiciousAttachments = 1;
    indicators.push({
      name: 'Suspicious Attachment Mention',
      severity: 'high',
      description: 'Mentions or contains high-risk file types (.zip, .exe, etc.)'
    });
  }

  // Extract URLs from content
  const urlRegex = /(?:https?:\/\/)[^\s]+|(?:www\.)[^\s]+|\b[a-zA-Z0-9.-]+\.(?:com|org|net|io|co|us|uk|gov|edu|info|biz|me|tv|shop|app|xyz|in|ac|ca|au|de)\b/gi;
  const urlMatches = content.match(urlRegex) || [];
  const domains = new Set<string>();
  const phishingUrlsKw = ['login', 'account', 'verify', 'secure', 'update', 'authenticate', 'confirm'];

  for (const url of urlMatches) {
    if (url.length > 50) features.urlLength = 1;
    if ((url.match(/\./g) || []).length >= 3) features.numDots = 1;
    
    if (phishingUrlsKw.some(kw => url.toLowerCase().includes(kw))) {
      features.urlKeywords = 1;
      indicators.push({
        name: 'Suspicious URL Keywords',
        severity: 'medium',
        description: 'URL contains common phishing keywords'
      });
    }

    try {
      const expanded = await expandShortUrl(url); // Attempt expansion
      if (expanded !== url) {
        features.linkDiscrepancy = 1;
        indicators.push({
          name: 'Hidden Redirect',
          severity: 'medium',
          description: `Shortened URL redirects to: ${expanded}`
        });
      }

      const domain = new URL(expanded.startsWith('http') ? expanded : `https://${expanded}`).hostname;
      domains.add(domain);
    } catch (e) {
      // Invalid URL, try to extract domain manually
      const domainMatch = url.match(/(?:https?:\/\/)?([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})/);
      if (domainMatch) domains.add(domainMatch[1]);
    }

    if (/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/.test(url)) {
      features.hasIp = 1;
      indicators.push({
        name: 'IP-Based URL',
        severity: 'high',
        description: 'Uses IP address instead of domain'
      });
    }
  }

  // Also get bare domains from content (Expanded TLDs)
  const bareMatches = content.match(/([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})\b/gi) || [];
  for (const match of bareMatches) {
    // Basic filter to avoid matching "ver.1.2.3" or similar non-domains
    if (!match.includes('..') && match.length > 3) {
      domains.add(match.toLowerCase());
    }
  }

  // --- FORENSICS: Fetch data for the first detected domain ---
  let forensics: ForensicsData | undefined;
  if (domains.size > 0) {
    const primaryDomain = Array.from(domains)[0];
    forensics = await getForensics(primaryDomain);

    // Forensics-based Logic Integration
    if (forensics.age.days && forensics.age.days < 30) {
      features.domainAge = 1;
      indicators.push({
        name: 'Newly Created Domain',
        severity: 'high',
        description: `Domain created only ${forensics.age.days} days ago`
      });
    }

    if (forensics.dns.mx.length === 0) {
      indicators.push({
        name: 'No Mail Server',
        severity: 'medium',
        description: 'Domain cannot receive emails (suspicious for a "bank" or "support")'
      });
    }
  }
  // -----------------------------------------------------------

  // Check each domain for punycode, free hosting, brand mismatches, and lookalikes
  const KNOWN_BRANDS_LOWER = KNOWN_BRANDS.map(b => b.toLowerCase());
  for (const domain of domains) {
    // 1. Punycode check
    if (domain.startsWith('xn--')) {
      features.punycode = 1;
      indicators.push({
        name: 'Punycode/IDN Homograph',
        severity: 'high',
        description: `Domain uses Punycode (${domain}) to spoof legitimate characters`
      });
    }

    // 2. Disposable Host check
    const freeHosts = ['000webhostapp.com', 'ngrok.io', 'firebaseapp.com', 'herokuapp.com', 'netlify.app', 'vercel.app', 'glitch.me', 'repl.co'];
    if (freeHosts.some(host => domain.endsWith(host)) && !domain.includes('phishguard7')) { // avoid flagging ourselves
      features.disposableHost = 1;
      indicators.push({
        name: 'Disposable/Free Hosting',
        severity: 'medium',
        description: `Domain is hosted on a free or temporary platform (${domain})`
      });
    }

    // 3. Brand Context Mismatch
    if (features.brandMismatch === 0) {
      for (const brand of KNOWN_BRANDS_LOWER) {
        if (lowerContent.includes(brand) && !domain.includes(brand) && !['000webhostapp.com', 'ngrok.io', 'firebaseapp.com'].some(h => domain.endsWith(h))) {
          features.brandMismatch = 1;
          indicators.push({
            name: 'Brand Context Mismatch',
            severity: 'high',
            description: `Message claims to be from '${brand}' but links to an unrelated domain (${domain})`
          });
          break;
        }
      }
    }

    // 4. Lookalike check
    const lookalikeCheck = detectLookalikeAttack(domain);
    if (lookalikeCheck.isLookalike) {
      features.lookalike = 1;
      const subs = lookalikeCheck.substitutions?.slice(0, 2).join(', ') || 'various';
      indicators.push({
        name: 'Lookalike Domain Attack',
        severity: 'high',
        description: `Domain "${domain}" is a lookalike of "${lookalikeCheck.targetBrand}" with substitutions: ${subs}`
      });
    }
  }

  // Logistic Regression Probability
  const probability = calculateLogisticRegression(features);
  const score = Math.round(probability * 100);

  const label: 'safe' | 'suspicious' | 'phishing' =
    probability >= 0.5 ? 'phishing' : probability >= 0.3 ? 'suspicious' : 'safe';

  // Confidence increases if probability is extreme
  const pDiff = Math.abs(probability - 0.5); // 0 to 0.5
  const confidence = Math.round((0.5 + pDiff) * 100) / 100;

  return {
    label,
    risk_percentage: score,
    confidence,
    input_type: type || 'auto',
    top_reasons: indicators.slice(0, 5).map(i => i.description),
    forensics,
    isFallback: true,
    details: {
      indicators,
      analysis_summary:
        label === 'phishing' ? 'Logistic Regression model predicts high probability of phishing. Do not interact.' :
          label === 'suspicious' ? 'Logistic Regression model flags potential risk. Exercise caution.' :
            'Logistic Regression model predicts this content is safe.'
    }
  };
}

export async function detectPhishing(content: string, type: 'auto' | 'url' | 'email' | 'sms' = 'auto'): Promise<DetectionResult> {
  const indicators: { name: string; severity: 'low' | 'medium' | 'high'; description: string }[] = [];
  let score = 0;

  // Extract URLs from content for the Cloud Function
  const urlRegex = /(?:https?:\/\/)[^\s]+|(?:www\.)[^\s]+|\b[a-zA-Z0-9.-]+\.(?:com|org|net|io|co|us|uk|gov|edu|info|biz|me|tv|shop|app|xyz|in|ac|ca|au|de)\b/gi;
  const urlMatches = content.match(urlRegex) || [];
  const urls = [...new Set(urlMatches)];

  let threat_audit: { scan_time: string; sources: Record<string, unknown> } | undefined;

  // Call Vercel serverless function for third-party API checks (keys stay server-side)
  if (urls.length > 0) {
    try {
      const response = await fetch('/api/detect-phishing', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ urls }),
      });

      if (response.ok) {
        const serverData = await response.json() as {
          indicators: { name: string; severity: 'low' | 'medium' | 'high'; description: string }[];
          threat_audit: { scan_time: string; sources: Record<string, unknown> } | null;
          score: number;
        };

        indicators.push(...serverData.indicators);
        score += serverData.score;
        if (serverData.threat_audit) {
          threat_audit = serverData.threat_audit;
        }
      }
    } catch (e) {
      console.warn('Cloud Function detectPhishing call failed (falling back to local only):', e);
    }
  }

  // Combine with Local Heuristics (still runs client-side — no API keys needed)
  const localResult = await performLocalDetection(content, type);
  
  const mergedIndicators = [...indicators, ...localResult.details.indicators];
  const finalScore = Math.min(score + localResult.risk_percentage, 100);
  const finalLabel = finalScore >= 50 ? 'phishing' : finalScore >= 20 ? 'suspicious' : 'safe';

  return {
    label: finalLabel,
    risk_percentage: finalScore,
    confidence: Math.round(Math.min(0.5 + mergedIndicators.length * 0.1, 0.95) * 100) / 100,
    input_type: type || 'auto',
    top_reasons: mergedIndicators.slice(0, 5).map(i => i.description),
    forensics: localResult.forensics,
    threat_audit: threat_audit || undefined,
    details: {
      indicators: mergedIndicators,
      analysis_summary: finalLabel === 'phishing' ? 'High risk determined by API integrations and heuristics.' :
                        finalLabel === 'suspicious' ? 'Content appears suspicious based on heuristics or low-level API flags.' :
                        'No major threat signatures matched.'
    }
  };
}

// ============ Local Storage Functions (for anonymous users) ============
const HISTORY_KEY = 'phishguard_scan_history';
const MAX_HISTORY_ITEMS = 50;

export function getLocalScanHistory(): ScanHistoryItem[] {
  try {
    const stored = localStorage.getItem(HISTORY_KEY);
    return stored ? JSON.parse(stored) : [];
  } catch {
    return [];
  }
}

export function addToLocalScanHistory(content: string, result: DetectionResult): ScanHistoryItem {
  const history = getLocalScanHistory();

  const newItem: ScanHistoryItem = {
    id: generateUUID(),

    content,
    content_preview: content.length > 100 ? content.substring(0, 100) + '...' : content,
    result,
    scanned_at: new Date().toISOString()
  };

  const updated = [newItem, ...history].slice(0, MAX_HISTORY_ITEMS);

  try {
    localStorage.setItem(HISTORY_KEY, JSON.stringify(updated));
  } catch {
    localStorage.setItem(HISTORY_KEY, JSON.stringify(updated.slice(0, 10)));
  }

  return newItem;
}

export function clearLocalScanHistory(): void {
  localStorage.removeItem(HISTORY_KEY);
}

export function deleteLocalScanHistoryItem(id: string): void {
  const history = getLocalScanHistory();
  const updated = history.filter(item => item.id !== id);
  localStorage.setItem(HISTORY_KEY, JSON.stringify(updated));
}

// ============ Database Functions (for authenticated users) ============

export async function getDbScanHistory(): Promise<ScanHistoryItem[]> {
  const user = auth.currentUser;
  if (!user) return [];

  try {
    const q = query(
      collection(db, "scan_history"),
      where("user_id", "==", user.uid),
      orderBy('created_at', 'desc'),
      limit(MAX_HISTORY_ITEMS)
    );
    const querySnapshot = await getDocs(q);
    
    return querySnapshot.docs.map(doc => {
      const row = doc.data();
      return {
        id: doc.id,
        content: row.content,
        content_preview: row.content.length > 100 ? row.content.substring(0, 100) + '...' : row.content,
        result: {
          label: row.label as DetectionResult['label'],
          risk_percentage: Number(row.risk_percentage),
          confidence: Number(row.confidence),
          input_type: row.input_type,
          top_reasons: row.top_reasons as string[],
          details: row.details as DetectionResult['details'],
        },
        scanned_at: row.created_at,
      };
    });
  } catch (error) {
    console.error('Failed to fetch scan history:', error);
    return [];
  }
}

export async function addToDbScanHistory(content: string, result: DetectionResult): Promise<ScanHistoryItem | null> {
  const user = auth.currentUser;

  if (!user) {
    return null;
  }

  try {
    const docRef = await addDoc(collection(db, "scan_history"), {
      user_id: user.uid,
      content,
      input_type: result.input_type,
      label: result.label,
      risk_percentage: result.risk_percentage,
      confidence: result.confidence,
      top_reasons: result.top_reasons,
      details: result.details,
      created_at: new Date().toISOString()
    });

    const newData = {
      id: docRef.id,
      content,
      content_preview: content.length > 100 ? content.substring(0, 100) + '...' : content,
      result,
      scanned_at: new Date().toISOString(),
    };
    return newData;
  } catch (error) {
    console.error('Failed to save scan history:', error);
    return null;
  }
}

export async function deleteDbScanHistoryItem(id: string): Promise<void> {
  try {
    await deleteDoc(doc(db, "scan_history", id));
  } catch (error) {
    console.error('Failed to delete scan history item:', error);
  }
}

export async function clearDbScanHistory(): Promise<void> {
  const user = auth.currentUser;
  if (!user) return;

  try {
    const q = query(collection(db, "scan_history"), where("user_id", "==", user.uid));
    const querySnapshot = await getDocs(q);
    const deletePromises = querySnapshot.docs.map(document => deleteDoc(doc(db, "scan_history", document.id)));
    await Promise.all(deletePromises);
  } catch (error) {
    console.error('Failed to clear scan history:', error);
  }
}

// ============ Unified API (auto-switches based on auth) ============

export async function getScanHistory(userId: string | null): Promise<ScanHistoryItem[]> {
  const isAnon = auth.currentUser?.isAnonymous;
  if (userId && !isAnon) {
    return getDbScanHistory();
  }
  return getLocalScanHistory();
}

export async function addToScanHistory(content: string, result: DetectionResult, userId: string | null): Promise<ScanHistoryItem> {
  const isAnon = auth.currentUser?.isAnonymous;
  if (userId && !isAnon) {
    const dbItem = await addToDbScanHistory(content, result);
    if (dbItem) return dbItem;
  }
  return addToLocalScanHistory(content, result);
}

export async function deleteScanHistoryItem(id: string, userId: string | null): Promise<void> {
  const isAnon = auth.currentUser?.isAnonymous;
  if (userId && !isAnon) {
    await deleteDbScanHistoryItem(id);
  } else {
    deleteLocalScanHistoryItem(id);
  }
}

export async function clearScanHistory(userId: string | null): Promise<void> {
  const isAnon = auth.currentUser?.isAnonymous;
  if (userId && !isAnon) {
    await clearDbScanHistory();
  } else {
    clearLocalScanHistory();
  }
}

// Migrate local history to database on sign in
export async function migrateLocalHistoryToDb(): Promise<number> {
  const localHistory = getLocalScanHistory();

  if (localHistory.length === 0) return 0;

  const user = auth.currentUser;
  if (!user) return 0;

  let migratedCount = 0;

  for (const item of localHistory) {
    try {
      await addDoc(collection(db, "scan_history"), {
        user_id: user.uid,
        content: item.content,
        input_type: item.result.input_type,
        label: item.result.label,
        risk_percentage: item.result.risk_percentage,
        confidence: item.result.confidence,
        top_reasons: item.result.top_reasons,
        details: item.result.details,
        created_at: item.scanned_at,
      });
      migratedCount++;
    } catch (error) {
      console.error('Error migrating item:', error);
    }
  }

  // Clear local storage after successful migration
  if (migratedCount > 0) {
    clearLocalScanHistory();
  }

  return migratedCount;
}
